global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using PhotoGallery_AspDotNet8_MVC.Models;
global using Microsoft.AspNetCore.Identity;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using PhotoGallery_AspDotNet8_MVC.DbContext;
global using PhotoGallery_AspDotNet8_MVC.ViewModels;